### ISSUE TITLE
Cron job redis_gather_metrics fails with Call to undefined function get_plugin_data()

### ISSUE THREAD

**Issue by dz0ny** [tillkruss/redis-cache#132]
Version: 1.5.2

Stacktrace:
```php
Call to undefined function get_plugin_data()

@ wp-cron.php at line 138
@ wp-includes/plugin.php in do_action_ref_array at line 544
@ wp-includes/class-wp-hook.php in do_action at line 312
@ wp-includes/class-wp-hook.php in apply_filters at line 288
@ wp-content/plugins/redis-cache/redis-cache.php in gather_metrics at line 358
@ wp-content/plugins/redis-cache/redis-cache.php in get_redis_version at line 218
@ wp-content/plugins/redis-cache/redis-cache.php in validate_object_cache_dropin at line 160
155. 
156.         if ( ! $this->object_cache_dropin_exists() ) {
157.             return false;
158.         }
159. 
160.         > $dropin = get_plugin_data( WP_CONTENT_DIR . '/object-cache.php' );
161.         $plugin = get_plugin_data( plugin_dir_path( __FILE__ ) . '/includes/object-cache.php' );
162. 
163.         if ( strcmp( $dropin[ 'PluginURI' ], $plugin[ 'PluginURI' ] ) !== 0 ) {
164.             return false;
165.         }
```

**Comment by rba7sp** [comment]
I have the same issue once a day triggered by wp-cron.php

```php
PHP Fatal error:  Uncaught Error: Call to undefined function get_plugin_data() in wp-content/plugins/redis-cache/redis-cache.php:160
Stack trace:
#0 wp-content/plugins/redis-cache/redis-cache.php(218): RedisObjectCache->validate_object_cache_dropin()
#1 wp-content/plugins/redis-cache/redis-cache.php(358): RedisObjectCache->get_redis_version()
#2 wp-includes/class-wp-hook.php(288): RedisObjectCache->gather_metrics()
#3 wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#4 wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#5 wp-cron.php(138): do_action_ref_array('redis_gather_me...', Array)
#6 {main}
  thrown in wp-content/plugins/redis-cache/redis-cache.php on line 160`

**Comment by tillkruss** [comment]
Thanks for reporting this. Sadly I can't reproduce this.

Are you using any special WP Cron set up?

Could you try adding a line to `/plugins/redis-cache/redis-cache.php`?

```diff
class RedisObjectCache {
{
   public function __construct() {
   {
+     require_once ABSPATH . 'wp-admin/includes/plugin.php';

      load_plugin_textdomain( 'redis-cache', false, 'redis-cache/languages' );
   }
}
```

**Comment by tillkruss** [comment]
Or alternatively, try uploading this fixed version:

[redis-cache-132.zip](https://github.com/tillkruss/redis-cache/files/3880961/redis-cache-132.zip)

I'd like to test it with one of you before releasing a new version where I can reproduce the bug.

**Comment by rba7sp** [comment]
For debug reasons I have installed wp control. At the time of the error, the daily job 
redis_gather_metrics  RedisObjectCache->gather_metrics() was running.
I have added your line of code and run the job manually. It seems it solves the fatal error issue.

**Comment by tillkruss** [comment]
Thanks!

I'll release the fix today.
