### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method WP_Object_Cache::redis_status()

### ISSUE THREAD

**Issue by michaelryanmcneill** [tillkruss/redis-cache#72]
I'm getting a PHP Fatal Error with 1.3.8. I'm not sure what I'm missing, but I've made sure to update the object-cache.php file. From what I can tell, seems that object-cache.php isn't being included? Any thoughts?
 
```
PHP Fatal error:  Uncaught Error: Call to undefined method WP_Object_Cache::redis_status() in /opt/local/apache/appdata/wp-content/plugins/redis-cache/redis-cache.php:171
Stack trace:
#0 /opt/local/apache/appdata/wp-content/plugins/redis-cache/redis-cache.php(153): RedisObjectCache->get_redis_status()
#1 /opt/local/apache/appdata/wp-content/plugins/redis-cache/includes/admin-page.php(14): RedisObjectCache->get_status()
#2 /opt/local/apache/appdata/wp-content/plugins/redis-cache/redis-cache.php(92): require_once('/opt/local/apac...')
#3 /opt/local/apache/appdata/wp-includes/class-wp-hook.php(286): RedisObjectCache->show_admin_page('')
#4 /opt/local/apache/appdata/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /opt/local/apache/appdata/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /opt/local/apache/appdata/wp-admin/admin.php(224): do_action('settings_page_r...')
#7 /opt/local/apache/appdata/wp-admin/options-general.php(10): require_once('/opt/local/apac...')
#8 {main}
  thrown in /opt/local/apache/appdata/wp-content/plugins/redis-cache/redis-cache.php on line 171
```

**Comment by tillkruss** [comment]
Mhh, my guess is the `object-cache.php` you're using isn't actually the right one. Are you using any other cache plugins?

Can you try deleting the `wp-content/object-cache.php` and then acting the cache again?

**Comment by michaelryanmcneill** [comment]
I did that twice, verified that the md5sums matched and tried making it a symlink to the file in the plugin directory. All yield the same fatal error result.

**Comment by michaelryanmcneill** [comment]
Oh and no other caching plug-ins are enabled.

**Comment by tillkruss** [comment]
Can you post your `/wp-content/object-cache.php` file in here?

**Comment by michaelryanmcneill** [comment]
Absolutely, see this gist: https://gist.github.com/michaelryanmcneill/7f042afeae0a15b22966b89fe2b8d3f0

Also, here is the md5sum:
`37a0d02d0e0b7a04849a6b02d82be7bd  object-cache.php`

**Comment by michaelryanmcneill** [comment]
Also, what is confusing is, if I run it via WP-CLI, I see the following output:

```
$ wp redis status
Status: Connected
Client: Predis (v1.1.1)
```

**Comment by tillkruss** [comment]
Man. Where are you seeing that error?

**Comment by michaelryanmcneill** [comment]
In the PHP error log. To reproduce, I go to the WP-Admin -> Settings -> Redis page. The page fails to completely load because of the fatal error. Looking in the error log, I see an entry that shows that error and stack trace.

**Comment by tillkruss** [comment]
This is just really strange, I'm afraid I can't really do anything here without debugging this directly on your machine.

What I'd do is dump the `$wp_object_cache` global right on that admin page to see what is going on there.

**Comment by michaelryanmcneill** [comment]
Yeah, I mean, I dumped the `$wp_object_cache` global, but there's not much usable data in there. What exactly should I be looking for?

**Comment by tillkruss** [comment]
Call get_class_methods and get_object_vars maybe.

**Comment by tillkruss** [comment]
On that object.

**Comment by michaelryanmcneill** [comment]
Now we're getting somewhere though. Run via WP-CLI, the same result is:

```
$ wp redis status
array(20) {
  [0]=>
  string(11) "__construct"
  [1]=>
  string(12) "redis_status"
  [2]=>
  string(14) "redis_instance"
  [3]=>
  string(3) "add"
  [4]=>
  string(7) "replace"
  [5]=>
  string(6) "delete"
  [6]=>
  string(5) "flush"
  [7]=>
  string(3) "get"
  [8]=>
  string(9) "get_multi"
  [9]=>
  string(3) "set"
  [10]=>
  string(9) "increment"
  [11]=>
  string(4) "incr"
  [12]=>
  string(9) "decrement"
  [13]=>
  string(5) "stats"
  [14]=>
  string(9) "build_key"
  [15]=>
  string(21) "add_to_internal_cache"
  [16]=>
  string(23) "get_from_internal_cache"
  [17]=>
  string(14) "switch_to_blog"
  [18]=>
  string(17) "add_global_groups"
  [19]=>
  string(25) "add_non_persistent_groups"
}
Status: Connected
Client: Predis (v1.1.1)
```

**Comment by tillkruss** [comment]
That makes sense. I assume a server restart would have revealed that. That's for letting me know.
